language: elm
node_js: '10.15.3'
elm:
  - '0.19.0'

script:
  - elm-format --validate .
  - yarn test
  - echo "API_URL=$PLAYER_AID_API_URL" > .env
  - yarn build

deploy:
  provider: pages
  local_dir: ./build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
